package com.h4rsh41.paisatracker.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Enhanced salary record supporting multiple income sources per month.
 *
 * Each salary is now linked to a specific bank account and can have a source type
 * (e.g., primary job, freelance, bonus). This allows users to track multiple
 * income streams while maintaining proper account-level tracking.
 *
 * [receivedAt] is the timestamp when the user logged the salary.
 * [linkedAccountId] is the bank account where this salary is credited (required).
 * [sourceName] is a user-friendly name for this income source.
 * [sourceType] categorizes the income (PRIMARY, FREELANCE, BONUS, PASSIVE, OTHER).
 */
@Entity(tableName = "salary_records")
data class SalaryRecord(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    
    /** Salary amount (e.g., 75000.0) */
    val amount: Double,
    
    /** Timestamp when salary was logged (epoch ms) */
    val receivedAt: Long = System.currentTimeMillis(),
    
    /** Month (1-12) */
    val month: Int,
    
    /** Year (e.g., 2025) */
    val year: Int,
    
    /** Optional note/description */
    val note: String = "",
    
    /** Currency code */
    val currency: String = "INR",
    
    /** Whether this salary auto-generates next month */
    val isRecurring: Boolean = false,
    
    /** Bank account where salary is credited (REQUIRED for new records) */
    val linkedAccountId: Long = 0,
    
    /** Source type: PRIMARY, FREELANCE, BONUS, PASSIVE, OTHER */
    val sourceType: String = SalarySourceType.PRIMARY,
    
    /** Display name for this income source (e.g., "Tech Corp Salary") */
    val sourceName: String = "",
    
    /** Whether this was auto-generated by recurring logic */
    val autoGenerated: Boolean = false,
    
    /** Whether this salary is active for spending calculations */
    val isActive: Boolean = true,
    
    // Legacy field for backward compatibility (will be migrated to linkedAccountId)
    @Deprecated("Use linkedAccountId instead", ReplaceWith("linkedAccountId"))
    val recurringAccountId: Long? = null
)
